-- Supabase Schema for APK (Standalone Version)
-- This version does not depend on Supabase Auth (auth.users) for easier development.

-- 1. DROP EXISTING (Clean Slate)
DROP TABLE IF EXISTS public.notifications;
DROP TABLE IF EXISTS public.messages;
DROP TABLE IF EXISTS public.marketing_assets;
DROP TABLE IF EXISTS public.payout_requests;
DROP TABLE IF EXISTS public.activity_logs;
DROP TABLE IF EXISTS public.promo_codes;
DROP TABLE IF EXISTS public.reviews;
DROP TABLE IF EXISTS public.products;
DROP TABLE IF EXISTS public.categories;
DROP TABLE IF EXISTS public.profiles;

-- 2. PROFILES
CREATE TABLE public.profiles (
    id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
    email TEXT UNIQUE NOT NULL,
    password_hash TEXT NOT NULL,
    role TEXT DEFAULT 'customer' CHECK (role IN ('customer', 'promoter', 'moderator', 'admin')),
    status TEXT DEFAULT 'active' CHECK (status IN ('active', 'suspended', 'banned')),
    promo_code_used TEXT,
    discount_remaining NUMERIC DEFAULT 0,
    fidelity_points INTEGER DEFAULT 0,
    unpaid_balance NUMERIC DEFAULT 0,
    interests TEXT[] DEFAULT '{}',
    last_activity TIMESTAMPTZ DEFAULT NOW(),
    created_at TIMESTAMPTZ DEFAULT NOW()
);

-- 3. CATEGORIES
CREATE TABLE public.categories (
    id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
    name TEXT NOT NULL,
    slug TEXT UNIQUE NOT NULL,
    image_url TEXT,
    created_at TIMESTAMPTZ DEFAULT NOW()
);

-- 4. PRODUCTS
CREATE TABLE public.products (
    id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
    name TEXT NOT NULL,
    slug TEXT UNIQUE NOT NULL,
    description TEXT,
    price NUMERIC NOT NULL,
    discount_percentage NUMERIC DEFAULT 0,
    category_id UUID REFERENCES public.categories(id) ON DELETE SET NULL,
    stock_quantity INTEGER DEFAULT 0,
    rating NUMERIC DEFAULT 0,
    review_count INTEGER DEFAULT 0,
    images TEXT[] DEFAULT '{}',
    is_trending BOOLEAN DEFAULT FALSE,
    is_flash_deal BOOLEAN DEFAULT FALSE,
    flash_deal_end TIMESTAMPTZ,
    created_at TIMESTAMPTZ DEFAULT NOW()
);

-- 5. REVIEWS
CREATE TABLE public.reviews (
    id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
    product_id UUID REFERENCES public.products(id) ON DELETE CASCADE NOT NULL,
    user_id UUID REFERENCES public.profiles(id) ON DELETE CASCADE NOT NULL,
    rating INTEGER CHECK (rating >= 1 AND rating <= 5) NOT NULL,
    comment TEXT,
    is_verified_purchase BOOLEAN DEFAULT FALSE,
    created_at TIMESTAMPTZ DEFAULT NOW()
);

-- 6. PROMO CODES
CREATE TABLE public.promo_codes (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    code TEXT UNIQUE NOT NULL,
    creator_id UUID REFERENCES public.profiles(id) ON DELETE CASCADE NOT NULL,
    created_at TIMESTAMPTZ DEFAULT NOW()
);

-- 5. ACTIVITY LOGS
CREATE TABLE public.activity_logs (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id UUID REFERENCES public.profiles(id) ON DELETE CASCADE NOT NULL,
    action_type TEXT NOT NULL,
    details TEXT,
    created_at TIMESTAMPTZ DEFAULT NOW()
);

-- 6. PAYOUT REQUESTS
CREATE TABLE public.payout_requests (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    promoter_id UUID REFERENCES public.profiles(id) ON DELETE CASCADE NOT NULL,
    amount NUMERIC NOT NULL,
    status TEXT DEFAULT 'pending' CHECK (status IN ('pending', 'paid', 'rejected')),
    payment_method_details TEXT,
    created_at TIMESTAMPTZ DEFAULT NOW(),
    paid_at TIMESTAMPTZ
);

-- 7. MARKETING ASSETS
CREATE TABLE public.marketing_assets (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    title TEXT NOT NULL,
    type TEXT CHECK (type IN ('image', 'video')),
    url TEXT NOT NULL,
    created_at TIMESTAMPTZ DEFAULT NOW()
);

-- 8. MESSAGES
CREATE TABLE public.messages (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    sender_id UUID REFERENCES public.profiles(id) ON DELETE CASCADE NOT NULL,
    receiver_id UUID REFERENCES public.profiles(id) ON DELETE CASCADE, -- NULL for support
    content TEXT NOT NULL,
    is_read BOOLEAN DEFAULT FALSE,
    created_at TIMESTAMPTZ DEFAULT NOW()
);

-- 9. NOTIFICATIONS
CREATE TABLE public.notifications (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id UUID REFERENCES public.profiles(id) ON DELETE CASCADE NOT NULL,
    title TEXT NOT NULL,
    content TEXT NOT NULL,
    type TEXT CHECK (type IN ('referral', 'sale', 'payout', 'chat')),
    is_read BOOLEAN DEFAULT FALSE,
    created_at TIMESTAMPTZ DEFAULT NOW()
);

-- 10. SEED DATA
-- Insert Sample Profiles
-- Password for all is 'password123'
INSERT INTO public.profiles (id, email, password_hash, role, status) VALUES
('a0eebc99-9c0b-4ef8-bb6d-6bb9bd380a11', 'admin@example.com', '$2a$10$SfhYIDtn.iOuCW7zfoFLuuZHX6lja4lF4XA4JqNmpiH/.P3zB8JCa', 'admin', 'active'),
('b0eebc99-9c0b-4ef8-bb6d-6bb9bd380a12', 'promoter@example.com', '$2a$10$SfhYIDtn.iOuCW7zfoFLuuZHX6lja4lF4XA4JqNmpiH/.P3zB8JCa', 'promoter', 'active');

-- Insert Sample Categories
INSERT INTO public.categories (name, slug, image_url) VALUES
('Electronics', 'electronics', 'https://picsum.photos/seed/elec/200/200'),
('Accessories', 'accessories', 'https://picsum.photos/seed/acc/200/200'),
('Smart Gadgets', 'smart-gadgets', 'https://picsum.photos/seed/smart/200/200');

-- Insert Sample Products
INSERT INTO public.products (name, slug, price, description, stock_quantity, images, category_id, is_trending) VALUES
('Premium Wireless Headphones', 'premium-wireless-headphones', 299.99, 'High-fidelity audio with active noise cancellation.', 50, ARRAY['https://images.unsplash.com/photo-1505740420928-5e560c06d30e?w=800'], (SELECT id FROM public.categories WHERE slug = 'electronics'), true),
('Minimalist Smart Watch', 'minimalist-smart-watch', 199.50, 'Track your health and stay connected in style.', 30, ARRAY['https://images.unsplash.com/photo-1523275335684-37898b6baf30?w=800'], (SELECT id FROM public.categories WHERE slug = 'smart-gadgets'), true);

-- Insert Sample Marketing Assets
INSERT INTO public.marketing_assets (title, type, url) VALUES
('Summer Sale Banner', 'image', 'https://images.unsplash.com/photo-1555421689-491a97ff2040?w=1200'),
('Product Showcase Video', 'video', 'https://assets.mixkit.co/videos/preview/mixkit-electronic-components-of-a-computer-circuit-board-4437-large.mp4'),
('Promoter Welcome Guide', 'image', 'https://images.unsplash.com/photo-1434030216411-0b793f4b4173?w=1200');

-- 11. RLS POLICIES (Simplified for Development)
-- In a real app, you'd use auth.uid(), but since we're using a custom auth system,
-- we'll allow all operations for the anon role for now to ensure data is visible.
-- WARNING: This is for development only.

ALTER TABLE public.profiles ENABLE ROW LEVEL SECURITY;
CREATE POLICY "Allow all for anon on profiles" ON public.profiles FOR ALL USING (true);

ALTER TABLE public.categories ENABLE ROW LEVEL SECURITY;
CREATE POLICY "Allow all for anon on categories" ON public.categories FOR ALL USING (true);

ALTER TABLE public.products ENABLE ROW LEVEL SECURITY;
CREATE POLICY "Allow all for anon on products" ON public.products FOR ALL USING (true);

ALTER TABLE public.reviews ENABLE ROW LEVEL SECURITY;
CREATE POLICY "Allow all for anon on reviews" ON public.reviews FOR ALL USING (true);

ALTER TABLE public.promo_codes ENABLE ROW LEVEL SECURITY;
CREATE POLICY "Allow all for anon on promo_codes" ON public.promo_codes FOR ALL USING (true);

ALTER TABLE public.activity_logs ENABLE ROW LEVEL SECURITY;
CREATE POLICY "Allow all for anon on activity_logs" ON public.activity_logs FOR ALL USING (true);

ALTER TABLE public.payout_requests ENABLE ROW LEVEL SECURITY;
CREATE POLICY "Allow all for anon on payout_requests" ON public.payout_requests FOR ALL USING (true);

ALTER TABLE public.marketing_assets ENABLE ROW LEVEL SECURITY;
CREATE POLICY "Allow all for anon on marketing_assets" ON public.marketing_assets FOR ALL USING (true);

ALTER TABLE public.messages ENABLE ROW LEVEL SECURITY;
CREATE POLICY "Allow all for anon on messages" ON public.messages FOR ALL USING (true);

ALTER TABLE public.notifications ENABLE ROW LEVEL SECURITY;
CREATE POLICY "Allow all for anon on notifications" ON public.notifications FOR ALL USING (true);

-- Enable Realtime
ALTER PUBLICATION supabase_realtime ADD TABLE public.profiles;
ALTER PUBLICATION supabase_realtime ADD TABLE public.messages;
ALTER PUBLICATION supabase_realtime ADD TABLE public.notifications;
